services:
  InventoryDB:
    image: postgres
    container_name: InventoryDB
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=${INVENTORY_POSTGRES_PASSWORD}
    networks:
      - BookRental

  RentalDB:
    image: postgres
    container_name: RentalDB
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${RENTAL_POSTGRES_PASSWORD}
    networks:
      - BookRental

  LGTM:
    image: grafana/otel-lgtm:latest
    container_name: LGTM
    ports:
      - 3000:3000
      - 4317:4317
      - 4318:4318
    networks:
      - BookRental

  Kafka:
    image: confluentinc/confluent-local:7.6.0
    container_name: confluent-local-broker
    ports:
      - 5550:5550
      - 8082:8082
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://confluent-local-broker:9092,PLAINTEXT_HOST://localhost:5550
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@confluent-local-broker:9093
      - KAFKA_LISTENERS=PLAINTEXT://confluent-local-broker:9092,CONTROLLER://confluent-local-broker:9093,PLAINTEXT_HOST://0.0.0.0:5550
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
      - KAFKA_REST_HOST_NAME=rest-proxy
      - KAFKA_REST_LISTENERS=http://0.0.0.0:8082
      - KAFKA_REST_BOOTSTRAP_SERVERS=confluent-local-broker:9092
      - LANG=C.UTF-8
      - UB_CLASSPATH=/usr/share/java/cp-base-lite/*
      - KAFKA_ZOOKEEPER_CONNECT=
      - CLUSTER_ID=
    networks:
      - BookRental

  init-InventoryDB:
    image: init-inventorydb:latest
    build: infrastructure/database/Inventory
    depends_on:
      - InventoryDB
    environment:
      - PGPASSWORD=${INVENTORY_POSTGRES_PASSWORD}
    networks:
      - BookRental

  init-RentalDB:
    image: init-rentaldb:latest
    build: infrastructure/database/Rental
    depends_on:
      - RentalDB
    environment:
      - PGPASSWORD=${RENTAL_POSTGRES_PASSWORD}
    networks:
      - BookRental

  init-Kafka:
    image: confluentinc/confluent-local:7.6.0
    depends_on:
      - Kafka
    entrypoint: [ "/bin/sh", "-c" ]
    command: |
      "
      echo 'waiting for Kafka...';
      while ! kafka-topics --bootstrap-server Kafka:9092 --list; do sleep 10; done;
      echo 'Kafka ready. Creating topics...';
      kafka-topics --bootstrap-server Kafka:9092 --create --if-not-exists --topic book_management --replication-factor 1 --partitions 1;
      kafka-topics --bootstrap-server Kafka:9092 --create --if-not-exists --topic book_available --replication-factor 1 --partitions 1;
      kafka-topics --bootstrap-server Kafka:9092 --create --if-not-exists --topic book_returned --replication-factor 1 --partitions 1;
      kafka-topics --bootstrap-server Kafka:9092 --create --if-not-exists --topic pending_confirmation --replication-factor 1 --partitions 1;
      kafka-topics --bootstrap-server Kafka:9092 --create --if-not-exists --topic confirmed_rental --replication-factor 1 --partitions 1;
      "
    networks:
      - BookRental

networks:
  BookRental:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.15.0/24
          gateway: 10.0.15.1