CREATE ROLE "API" WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  NOBYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:cwi3hnrrgdYGtr56Uy7xiQ==$ptapnVqME/ARvY9F8+c3NxQl+qniIgs1T+OOLHZXB+k=:or/8+tzF/WuDFb3MM8rS0z5Uhe4kLllMaC+zpenc3VM=';

CREATE ROLE analysis_inventory WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  NOBYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:VbW0acpJJfvJTU6XyB6Ndw==$J7oJSjpUkDxocjunymLAY5NDWXpHYCw4jJtOObVi1uo=:ALMu8MlejRBdJ5Gsm3OUvlgnEvgL+aA6HcbaJ133Rqc=';

GRANT CONNECT ON DATABASE "Inventory" TO "API";
GRANT CONNECT ON DATABASE "Inventory" TO analysis_inventory;
GRANT ALL ON DATABASE "Inventory" TO postgres;

GRANT USAGE ON SCHEMA inventory TO "API";
GRANT USAGE ON SCHEMA inventory TO analysis_inventory;
GRANT ALL ON SCHEMA inventory TO postgres;