
CREATE ROLE "API" WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  NOBYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:IviSnJ0ANg6uLtnMUh05jQ==$Erp4pkM8L1hUSN7igBgxSNbqlbFlHH6ER9kiaCNl1B0=:j87jDvf9ENrlWUJVpHYbLtd3NIkDDAOt8KTVTwS2V/I=';

CREATE ROLE analysis_rental WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  NOBYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:oMdDSTiUjlPeYD72+Q3HhA==$C6aZnhoju2gUX89d2nRQ5IGf9Tyt14S85jXPjLNyYVM=:OLRbf/2oS2wgTsTY0OgolhuWfUjmVWrjKZ9NirvsgkI=';

GRANT CONNECT ON DATABASE "Rental" TO "API";
GRANT CONNECT ON DATABASE "Rental" TO analysis_rental;
GRANT ALL ON DATABASE "Rental" TO postgres;

GRANT USAGE ON SCHEMA rental TO "API";
GRANT USAGE ON SCHEMA rental TO analysis_rental;
GRANT ALL ON SCHEMA rental TO postgres;